title: David Castro
timezone: UTC
email: david.castro.moraga@gmail.com
description: David Castro Moraga, Researcher with focus in plant response to drought stress & plant-microbiome interactions.
baseurl: ''
url: http://davcastrom.github.io
#twitter_username: DavidCastro
#github_username: DavidCastro
#linkedin_username: DavidCastro
#researchgate_username: DavidCastro
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
